{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-goodpractice
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/goodpractice_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/goodpractice/goodpractice_{{ version }}.tar.gz
  sha256: 44a0bc053261befbd91c9fabf9c08f89c1cc0d8d6545311b0304a470ffcccede

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-covr
    - r-curl
    - r-cyclocomp >=1.1.0
    - r-desc
    - r-jsonlite
    - r-lintr >=3.0.0
    - r-praise
    - r-rcmdcheck
    - r-roxygen2
    - r-rstudioapi
    - r-spelling
    - r-treesitter
    - r-treesitter.r
    - r-urlchecker
    - r-whoami
    - r-withr
  run:
    - r-base
    - r-cli
    - r-covr
    - r-curl
    - r-cyclocomp >=1.1.0
    - r-desc
    - r-jsonlite
    - r-lintr >=3.0.0
    - r-praise
    - r-rcmdcheck
    - r-roxygen2
    - r-rstudioapi
    - r-spelling
    - r-treesitter
    - r-treesitter.r
    - r-urlchecker
    - r-whoami
    - r-withr

test:
  commands:
    - $R -e "library('goodpractice')"           # [not win]
    - "\"%R%\" -e \"library('goodpractice')\""  # [win]

about:
  home: https://docs.ropensci.org/goodpractice/
  dev_url: https://github.com/ropensci-review-tools/goodpractice
  license: MIT
  summary: Give advice about good practices when building R packages. Advice includes functions and syntax to avoid, package structure, code complexity, code formatting, etc.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - russHyde
