appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: e67tFTNc0Lww43ZHKLe+JpA40LRFxrP0H9OKQ6Zetu4T1hdoz72yzi1Aym47x6WuAhl6F9lcIwPVF0dcn2xRPQQyCTn9UiHKROzl2bEaDRfN4lidZVFEHRMrsxLzNKYk1153nG1NT0kdlFEZaY1K2KNRsaRdEFsEMMLMyA149M6/Y2E7ENTE+9MQh6WljJ9jkReORV715RYFpy9gUZdxzAWr654nTYW8JI34H2l0tRDgEfLTMAW9frmIsdRqLUeoPJ/NKjYlrdUKlSurkgml7Qujy8Rpw9nPU3D4D4hE9J3pBn3OdBP2F3iIsDlToei8Y8niHULHMozALQ/+FtkKmvmE2MrO9/f/EQ3yMRqkptkJXJAgPGZ4D4SX0EFF0mg4WZygPQuM1VaFfn5WFE6ed34OT+b8xiIh2yKuk7UuPcWkmvz+kYSdbS/dKkEZ6wrRtr6XLQNELBcRZ/lH+sdm0wofxZAdxa6Cpvodh3V4cU7mq97Rdpts8JxFU4BgYh5IoHVOhz18+XNgNYIDjbrRJOatS85CLCbQU4ENm/cYk/4SGMPRF//WhhPkFltYwJXRVfIZV0pgxd/ZGqYvKW3GdgCLjuyLitJwyK+hZkY9VMzJN0K6W8nLXz7RpV1RmOenXv2IezGEEiv5RGiMGJlOzimIQZjmXg3bibJl0LsHUgs=
